name: Deploy on Main Merge

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Pull latest changes
        working-directory: /home/ubuntu  
        run: |
          touch Hello2
          rm Hello
          
