name: Deploy on Main Merge

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Create File
        working-directory: /home/ubuntu  
        run: |
          touch Hello3
          rm Hello2
          
